[Feature] QRCode Page
NTU-Art-Fest-29th-Easter-Egg/NTU-ArtFest-29th-Easter-Egg pull request #21
Opened 2024-04-15 16:54 UTC by littlechintw

- [x] Fix to new page
- [x] Show QRCode
- [x] If use phone can jump to home page

2024-04-17 11:38 UTC, garyellow commented
> @garyellow @fatbrother 阿尷尬，a1b88ba 應該要在另一個 branch

要在哪個？？

2024-04-17 12:00 UTC, garyellow requested changes

2024-04-17 12:00 UTC, garyellow commented on src/views/ShareWithQRCodeView.vue
> +        window.location.href = '/'
是不是用 router push 或 replace 去變更頁面比較好(不會刷新整個網頁(?
如果要改可以連 app.vue 那邊的一起改

2024-04-17 16:20 UTC, littlechintw commented on src/views/ShareWithQRCodeView.vue
> +        window.location.href = '/'
我是用你的方式做（X

2024-04-18 06:48 UTC, garyellow commented on src/App.vue
> +import router from './router'
一般好像是用 [useRouter](https://router.vuejs.org/zh/guide/advanced/composition-api)
這樣能跑也沒啥問題就是了
看要不要改

2024-04-18 06:48 UTC, garyellow commented on src/views/ShareWithQRCodeView.vue
> +import router from '../router'
ditto

2024-04-18 07:13 UTC, littlechintw commented on src/App.vue
> +import router from './router'
這部分你的 code，有時間你可以先修

2024-04-18 17:02 UTC, garyellow approved these changes

2024-04-18 17:02 UTC, merged

2024-04-18 17:06 UTC, garyellow commented on src/App.vue
> +import router from './router'
我直接處裡掉了
有問題再調整